import './modules/menu';
import './modules/hero';
import './modules/popup';
import './modules/programs';
import './modules/news';
import './modules/reviews';
import './modules/validation';
import './modules/select';
import './modules/phone-mask';
